FROM ros:humble

RUN apt update -y && apt install -y \
    ros-humble-xacro \
    ros-humble-ros-gz-sim \
    ros-humble-ros-gz-bridge \
    ros-humble-ros-gz \
    ros-humble-rqt-image-view \
    ros-humble-slam-toolbox \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-tf-transformations \
    python3-transforms3d \
    # --- vision / aruco ---
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    ros-humble-tf2-geometry-msgs \
    ros-humble-std-srvs \
    python3-opencv \
    python3-numpy \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/np\.float)/np.float64)/g' \
    /usr/lib/python3/dist-packages/transforms3d/quaternions.py \
    /usr/lib/python3/dist-packages/transforms3d/reflections.py